name: "env2"
robot_radius: 0.345
goal_tolerance: 0.5

start: [5.89, 1.47]
goal: [9.74, 9.71]

# List of rectangular obstacles defined as [cx, cy, width, height]
obstacles: [
[12.0000, 1.5330, 0.5, 0.5],
[11.7630, 1.9774, 0.5, 0.5],
[11.5260, 2.4219, 0.5, 0.5],
[11.2890, 2.8663, 0.5, 0.5],
[10.5520, 3.3108, 0.5, 0.5],
[10.8150, 3.7552, 0.5, 0.5],
[10.5780, 4.1997, 0.5, 0.5],
[10.3410, 4.6441, 0.5, 0.5],
[10.1040, 5.0886, 0.5, 0.5],
[9.8670, 5.5330, 0.5, 0.5],
[9.8670, 5.5330, 0.5, 0.5],
[10.3410, 5.3701, 0.5, 0.5],
[10.8150, 5.2072, 0.5, 0.5],
[11.2890, 5.0443, 0.5, 0.5],
[11.7630, 4.8814, 0.5, 0.5],
[12.2370, 4.7186, 0.5, 0.5],
[12.7110, 4.5557, 0.5, 0.5],
[13.1850, 4.3928, 0.5, 0.5],
[13.6590, 4.2299, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[13.7775, 3.6447, 0.5, 0.5],
[13.4220, 3.2223, 0.5, 0.5],
[13.0665, 2.8000, 0.5, 0.5],
[12.7110, 2.3777, 0.5, 0.5],
[12.3555, 1.9553, 0.5, 0.5],
[12.0000, 1.5330, 0.5, 0.5],
[12.0000, 1.5330, 0.5, 0.5],
[12.3555, 1.9553, 0.5, 0.5],
[12.7110, 2.3777, 0.5, 0.5],
[13.0665, 2.8000, 0.5, 0.5],
[13.4220, 3.2223, 0.5, 0.5],
[13.7775, 3.6447, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[14.6497, 3.9420, 0.5, 0.5],
[15.1665, 3.8170, 0.5, 0.5],
[15.6832, 3.6920, 0.5, 0.5],
[16.2000, 3.5670, 0.5, 0.5],
[16.7167, 3.4420, 0.5, 0.5],
[17.2335, 3.3170, 0.5, 0.5],
[17.7503, 3.1920, 0.5, 0.5],
[18.2670, 3.0670, 0.5, 0.5],
[18.2670, 3.0670, 0.5, 0.5],
[17.7447, 2.9392, 0.5, 0.5],
[17.2225, 2.8113, 0.5, 0.5],
[16.7003, 2.6835, 0.5, 0.5],
[16.1780, 2.5557, 0.5, 0.5],
[15.6557, 2.4278, 0.5, 0.5],
[15.1335, 2.3000, 0.5, 0.5],
[14.6113, 2.1722, 0.5, 0.5],
[14.0890, 2.0443, 0.5, 0.5],
[13.5667, 1.9165, 0.5, 0.5],
[13.0445, 1.7887, 0.5, 0.5],
[12.5222, 1.6608, 0.5, 0.5],
[12.0000, 1.5330, 0.5, 0.5],
[18.2670, 3.0670, 0.5, 0.5],
[17.7503, 3.1920, 0.5, 0.5],
[17.2335, 3.3170, 0.5, 0.5],
[16.7167, 3.4420, 0.5, 0.5],
[16.2000, 3.5670, 0.5, 0.5],
[15.6832, 3.6920, 0.5, 0.5],
[15.1665, 3.8170, 0.5, 0.5],
[14.6497, 3.9420, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[14.1330, 4.0670, 0.5, 0.5],
[14.3064, 4.5470, 0.5, 0.5],
[14.4798, 5.0270, 0.5, 0.5],
[14.6532, 5.5070, 0.5, 0.5],
[14.8266, 5.9870, 0.5, 0.5],
[15.0000, 6.4670, 0.5, 0.5],
[15.0000, 6.4670, 0.5, 0.5],
[15.3630, 6.0892, 0.5, 0.5],
[15.7260, 5.7114, 0.5, 0.5],
[16.0890, 5.3337, 0.5, 0.5],
[16.4520, 4.9559, 0.5, 0.5],
[16.8150, 4.5781, 0.5, 0.5],
[17.1780, 4.2003, 0.5, 0.5],
[17.5410, 3.8226, 0.5, 0.5],
[17.9040, 3.4448, 0.5, 0.5],
[18.2670, 3.0670, 0.5, 0.5],
[2.2000, 2.6670, 0.5, 0.5],
[2.3047, 3.1813, 0.5, 0.5],
[2.4094, 3.6956, 0.5, 0.5],
[2.5141, 4.2099, 0.5, 0.5],
[2.6189, 4.7241, 0.5, 0.5],
[2.7236, 5.2384, 0.5, 0.5],
[2.8283, 5.7527, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[3.1887, 5.8337, 0.5, 0.5],
[3.4443, 5.4003, 0.5, 0.5],
[3.7000, 4.9670, 0.5, 0.5],
[3.9557, 4.5337, 0.5, 0.5],
[4.2113, 4.1003, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[3.9002, 3.4170, 0.5, 0.5],
[3.3335, 3.1670, 0.5, 0.5],
[2.7668, 2.9170, 0.5, 0.5],
[2.2000, 2.6670, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[4.2113, 4.1003, 0.5, 0.5],
[3.9557, 4.5337, 0.5, 0.5],
[3.7000, 4.9670, 0.5, 0.5],
[3.4443, 5.4003, 0.5, 0.5],
[3.1887, 5.8337, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[3.4497, 6.5170, 0.5, 0.5],
[3.9665, 6.7670, 0.5, 0.5],
[4.4832, 7.0170, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[4.9239, 6.7527, 0.5, 0.5],
[4.8477, 6.2384, 0.5, 0.5],
[4.7716, 5.7241, 0.5, 0.5],
[4.6954, 5.2099, 0.5, 0.5],
[4.6193, 4.6956, 0.5, 0.5],
[4.5431, 4.1813, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[4.2113, 4.1003, 0.5, 0.5],
[3.9557, 4.5337, 0.5, 0.5],
[3.7000, 4.9670, 0.5, 0.5],
[3.4443, 5.4003, 0.5, 0.5],
[3.1887, 5.8337, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[3.4497, 6.5170, 0.5, 0.5],
[3.9665, 6.7670, 0.5, 0.5],
[4.4832, 7.0170, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[4.9239, 6.7527, 0.5, 0.5],
[4.8477, 6.2384, 0.5, 0.5],
[4.7716, 5.7241, 0.5, 0.5],
[4.6954, 5.2099, 0.5, 0.5],
[4.6193, 4.6956, 0.5, 0.5],
[4.5431, 4.1813, 0.5, 0.5],
[4.4670, 3.6670, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[4.4832, 7.0170, 0.5, 0.5],
[3.9665, 6.7670, 0.5, 0.5],
[3.4497, 6.5170, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[2.9330, 6.2670, 0.5, 0.5],
[3.2293, 6.6743, 0.5, 0.5],
[3.5257, 7.0817, 0.5, 0.5],
[3.8220, 7.4890, 0.5, 0.5],
[4.1183, 7.8963, 0.5, 0.5],
[4.4147, 8.3037, 0.5, 0.5],
[4.7110, 8.7110, 0.5, 0.5],
[5.0073, 9.1183, 0.5, 0.5],
[5.3037, 9.5257, 0.5, 0.5],
[5.6000, 9.9330, 0.5, 0.5],
[5.6000, 9.9330, 0.5, 0.5],
[5.4800, 9.3998, 0.5, 0.5],
[5.3600, 8.8666, 0.5, 0.5],
[5.2400, 8.3334, 0.5, 0.5],
[5.1200, 7.8002, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[5.1200, 7.8002, 0.5, 0.5],
[5.2400, 8.3334, 0.5, 0.5],
[5.3600, 8.8666, 0.5, 0.5],
[5.4800, 9.3998, 0.5, 0.5],
[5.6000, 9.9330, 0.5, 0.5],
[5.6000, 9.9330, 0.5, 0.5],
[5.9259, 9.5479, 0.5, 0.5],
[6.2518, 9.1628, 0.5, 0.5],
[6.5777, 8.7777, 0.5, 0.5],
[6.9036, 8.3926, 0.5, 0.5],
[7.2294, 8.0074, 0.5, 0.5],
[7.5553, 7.6223, 0.5, 0.5],
[7.8812, 7.2372, 0.5, 0.5],
[8.2071, 6.8521, 0.5, 0.5],
[8.5330, 6.4670, 0.5, 0.5],
[8.5330, 6.4670, 0.5, 0.5],
[8.0283, 6.5813, 0.5, 0.5],
[7.5236, 6.6956, 0.5, 0.5],
[7.0189, 6.8099, 0.5, 0.5],
[6.5141, 6.9241, 0.5, 0.5],
[6.0094, 7.0384, 0.5, 0.5],
[5.5047, 7.1527, 0.5, 0.5],
[5.0000, 7.2670, 0.5, 0.5],
[12.6000, 6.8000, 0.5, 0.5],
[12.9697, 7.1818, 0.5, 0.5],
[13.3395, 7.5636, 0.5, 0.5],
[13.7092, 7.9455, 0.5, 0.5],
[14.0789, 8.3273, 0.5, 0.5],
[14.4486, 8.7091, 0.5, 0.5],
[14.8184, 9.0909, 0.5, 0.5],
[15.1881, 9.4727, 0.5, 0.5],
[15.5578, 9.8545, 0.5, 0.5],
[15.9275, 10.2364, 0.5, 0.5],
[16.2973, 10.6182, 0.5, 0.5],
[16.6670, 10.5000, 0.5, 0.5],
[16.6670, 10.5000, 0.5, 0.5],
[16.1952, 10.8308, 0.5, 0.5],
[15.7233, 10.6615, 0.5, 0.5],
[15.2515, 10.4923, 0.5, 0.5],
[14.7796, 10.3231, 0.5, 0.5],
[14.3078, 10.1538, 0.5, 0.5],
[13.8359, 9.9846, 0.5, 0.5],
[13.3641, 9.8154, 0.5, 0.5],
[12.8922, 9.6462, 0.5, 0.5],
[12.4204, 9.4769, 0.5, 0.5],
[11.9485, 9.3077, 0.5, 0.5],
[11.4767, 9.1385, 0.5, 0.5],
[10.5048, 8.9692, 0.5, 0.5],
[10.5330, 8.8000, 0.5, 0.5],
[10.5330, 8.8000, 0.5, 0.5],
[10.9464, 8.4000, 0.5, 0.5],
[11.3598, 8.0000, 0.5, 0.5],
[11.7732, 7.6000, 0.5, 0.5],
[12.1866, 7.2000, 0.5, 0.5],
[12.6000, 6.8000, 0.5, 0.5]]